
[package]
name = 'ogl'
version = '0.1.0'
edition = '2021'

[build-dependencies]
gl_generator = '=0.14.0'

[dev-dependencies]
raw-gl-context = '=0.1.2'
winit = '=0.26.1'

[[test]]
name = 'test'
harness = false

